import {db,json,failure,sameOrigin,today} from '@/lib/server';
import {z} from 'zod';
const schema=z.object({id:z.string().uuid(),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),start:z.number().int().min(720).max(1320).refine(x=>x%30===0),tableId:z.number().int().positive(),guests:z.number().int().min(1).max(12),firstName:z.string().trim().min(2).max(80),lastName:z.string().trim().min(2).max(80),phone:z.string().regex(/^\+?[0-9]{9,15}$/),birthDay:z.number().int().min(1).max(31),birthMonth:z.number().int().min(1).max(12),consent:z.boolean(),notes:z.string().max(500),items:z.array(z.object({id:z.string().max(80),qty:z.number().int().min(1).max(20)})).max(30)});
export async function POST(r:Request){if(!sameOrigin(r))return json({error:'მოთხოვნა უარყოფილია'},403);try{const parsed=schema.safeParse(await r.json());if(!parsed.success)return json({error:'შეამოწმეთ შეყვანილი მონაცემები'},400);const b=parsed.data;
const birthday=new Date(Date.UTC(2000,b.birthMonth-1,b.birthDay));if(birthday.getUTCMonth()!==b.birthMonth-1)return json({error:'დაბადების დღის თარიღი არასწორია'},400);
const stamp=`${b.date}T${String(Math.floor(b.start/60)).padStart(2,'0')}:${String(b.start%60).padStart(2,'0')}:00+04:00`;const dt=new Date(stamp);if(!Number.isFinite(+dt)||b.date<today()||+dt<Date.now()||+dt>Date.now()+90*86400000||new Date(b.date+'T12:00:00Z').toISOString().slice(0,10)!==b.date)return json({error:'აირჩიეთ მომავალი დრო, შემდეგი 90 დღის ფარგლებში'},400);
const existing=await db().prepare('SELECT id FROM bookings WHERE id=?').bind(b.id).first();if(existing)return json({id:b.id});
const table=await db().prepare('SELECT * FROM dining_tables WHERE id=? AND active=1').bind(b.tableId).first();if(!table||Number(table.capacity)<b.guests)return json({error:'აირჩიეთ შესაბამისი მაგიდა'},400);
const items=[];const seen=new Set();for(const i of b.items){if(seen.has(i.id))return json({error:'განმეორებითი კერძი'},400);seen.add(i.id);const m=await db().prepare('SELECT id,name,price FROM menu_items WHERE id=? AND active=1').bind(i.id).first();if(!m)return json({error:'მენიუ შეიცვალა. განაახლეთ არჩევანი.'},409);items.push({...m,qty:i.qty});}
const now=new Date().toISOString();const ops=[db().prepare('INSERT INTO bookings (id,date,start,end,table_id,guests,first_name,last_name,phone,birth_day,birth_month,consent,consent_at,items,notes,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(b.id,b.date,b.start,b.start+120,b.tableId,b.guests,b.firstName,b.lastName,b.phone,b.birthDay,b.birthMonth,b.consent?1:0,b.consent?now:null,JSON.stringify(items),b.notes,'confirmed',now)];for(let m=b.start;m<b.start+120;m+=30)ops.push(db().prepare('INSERT INTO booking_slots (id,booking_id,table_id,date,minute) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),b.id,b.tableId,b.date,m));
try{await db().batch(ops);}catch(e){if(String(e).includes('UNIQUE constraint failed'))return json({error:'ეს მაგიდა ახლახან დაიჯავშნა. გთხოვთ აირჩიოთ სხვა.',conflict:true},409);throw e;}return json({id:b.id},201);
}catch(e){return failure(e);}}
